import os
print(os.getenv("TESTPASS"))
print("welecome to python")
print("welecome to python")
print("welecome to python")
print("hello")
print("i finished my task")
print("i know what's git and github")
print("i finished cursor set up successfully")
print("i can start my python class today")
